<a href="https://colab.research.google.com/github/she-DATAnalysis/module-1/blob/master/Solution_of_Exercise_4_Statistics_and_random_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Solution  - Exercise #4: Statistics and random sampling

###Aim: Use NumPy arrays in statistics and randomize samples

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Find the median of an array.
*   Find the correlation coefficient of an array.

*   Generate random sample from normal distribution.
*   Reordering array elements.


### First, import Numpy as np:




In [0]:
import numpy as np



### 1. Let’s look at array statistics.
Read “Statistics” on page 19 and then:





>(a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a" :







In [0]:
# Your Code Here#
a = np.array([range(4), range(10,14)])

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


>(b) Print the median of "a" :


In [0]:
# Your Code Here#
print(np.median(a))

6.5




>(c)   Print the correlation coefficient of "a":



In [0]:
# Your Code Here#
print(np.corrcoef(a))

[[1. 1.]
 [1. 1.]]


###2. Let's generate random samples.
Read “Random numbers” (pages 19-21) and then:





>(a)  Create a random array of shape (2, 4):




In [0]:
# Your Code Here#
arr = np.random.rand(2,4)



>(b)  Use a function that selects a random integer between 2 to 10:




In [0]:
# Your Code Here#
print(np.random.randint(2, 10))

2




>(c)  Generate a sample of size 40 from a standard normal distribution (with mean 0 and standard deviation 1), and assign it to the variable "b":




In [0]:
# Your Code Here#
b = np.random.normal(size=40)
print(b)

[ 1.63018957 -0.50043717  0.41852507  0.5301508   0.79424788 -0.62323111
  0.01570143 -0.91752443  0.74279124 -0.18542257 -2.53215314 -0.56567698
  1.40483923 -1.68668655 -0.89797351  0.22618748  1.11689969 -0.00577918
 -1.99481746 -0.38901697  0.89252569 -1.09802875 -2.03884317  0.67528243
  2.20093088 -0.36624699 -0.89754556  1.30182937 -0.78569996  1.5958596
 -1.57355116  0.62484397  0.50951684 -0.69620206  0.83482344  1.20703055
  0.28329772  1.60295509  0.8366242   1.19562729]




>(d) Randomly shuffle the elements in "b", and print "b":




In [0]:
# Your Code Here#
np.random.shuffle(b)
print(b)

[ 0.83482344 -1.68668655  2.20093088 -1.09802875  0.28329772  0.67528243
  0.74279124  1.40483923  0.22618748 -0.18542257 -1.99481746  0.8366242
  1.19562729  0.5301508  -0.38901697  1.20703055 -0.36624699  1.5958596
 -0.89797351  0.01570143  1.11689969 -0.50043717 -0.91752443 -0.00577918
 -2.03884317  0.62484397 -1.57355116 -0.78569996  0.89252569  0.79424788
  1.30182937  0.50951684 -2.53215314  0.41852507 -0.69620206 -0.89754556
  1.63018957  1.60295509 -0.62323111 -0.56567698]
