<a href="https://colab.research.google.com/github/she-DATAnalysis/module-1/blob/master/Solution_to_Exercise_3_Array_calculations_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #3: Array calculations and operations

###Aim: Use NumPy arrays in mathematical calculations

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Mathematical operations with arrays.
*   Mathematical operations mixing scalars and arrays.
*   Comparisons operators and Boolean operations on arrays.
*   Using the "where" method.
*   Mathematical operations on vectors.
*   Find coefficients and roots of polynomial.



First, import NumPy as np:







In [0]:
import numpy as np



### 1.  Let’s perform some array calculations.
**Read “Array mathematics” (pages 8-10) and then:**





> (a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a":








In [0]:
# Your Code Here#
a = np.array([range(4), range(10,14)])

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


> (b) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "b" :


In [0]:
# Your Code Here#
b = np.array([2, -1, 1, 0])

print(b)

[ 2 -1  1  0]



> (c) Multiply array "a" by "b" and view the results:




In [0]:
# Your Code Here#
print(a * b)


[[  0  -1   2   0]
 [ 20 -11  12   0]]


**Do you understand how NumPy has used its broadcasting feature to do the calculation even though the arrays are different shapes?**


It multiplied the vector 'b' by each dimention of matrix 'a' using the dot product:


[ 2 -1  1  0]*[ 0  1  2  3] = [0  -1  2  0]

[ 2 -1  1  0] * [10 11 12 13] = [ 20 -11  12   0]



> (d) Multiply array "b" by 100 and assign the result to the variable "b1":



In [0]:
# Your Code Here#
b1 = b * 100

print(b1)

[ 200 -100  100    0]




> (e) Multiply array "b" by 100.0 and assign the result to the variable "b2":



In [0]:
# Your Code Here#
b2 = b * 100.0

print(b2)

[ 200. -100.  100.    0.]




>(f) Print b1 == b2:





In [0]:
# Your Code Here#
print(b1 == b2)

[ True  True  True  True]


**Are they the same?**

yes




>(g) Why do they display differently? Interrogate the typecode of each array to find out why:



In [0]:
# Your Code Here#
print(b1.dtype, b2.dtype)

int64 float64


###2. Let's perform some operations on array.
Read the last code chunk on page 4 and read on until page 7 includes 
	Read “Basic array operations” (pages 11-12) and then:





> (a) Continue to use arrays "a" defined above:




In [0]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]




> (b) Print the sum, mean and the product of "a" in two different ways:




In [0]:
# Your Code Here#
print(a.sum(), a.mean(), a.prod())

print(np.sum(a), np.mean(a), np.prod(a))

52 6.5 0
52 6.5 0




>(c) Print the variance and the standard deviation of "a"in two different ways:




In [0]:
# Your Code Here#
print(a.var(), a.std())
print(np.var(a), np.std(a))

26.25 5.123475382979799
26.25 5.123475382979799


###3. Let’s look at array comparisons.
Read “Comparisons operators and value testing” (pages 12-14). Then:





>(a)  Create an array of values 0 to 9 and assign it to the variable "arr":




In [0]:
# Your Code Here#
arr = np.array(range(10))

print(arr)

[0 1 2 3 4 5 6 7 8 9]




>(b)  Print two different ways of expressing the condition where the array is less than 3:




In [0]:
# Your Code Here#
print(arr < 3)
print(np.less(arr, 3))

[ True  True  True False False False False False False False]
[ True  True  True False False False False False False False]




>(c)  Create a numpy condition where "arr" is less than 3 OR greater than 8:




In [0]:
# Your Code Here#
condition = np.logical_or(arr < 3, arr > 8)
print(condition)

[ True  True  True False False False False False False  True]




>(d)  Use the  *where*  function to create a new array where the value is arr * 5 if the above condition is True and arr * -5 where the condition is False:




In [0]:
# Your Code Here#
new_arr = np.where(condition, arr * 5, arr * -5)
print(new_arr)

[  0   5  10 -15 -20 -25 -30 -35 -40  45]


###4. Let’s look at item selection and manipulation.
Read “Array item selection and manipulation” (pages 14-16).






>(a)  Continue to use arrays "a" defined above:




In [0]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]




>(b)  Print an array contains all the values from "a" that are greater than 1:




In [0]:
# Your Code Here#
print(a[a > 1])

[ 2  3 10 11 12 13]




>(c)  Print an array contains all the values from "a" that are greater than 3 and smaller than 11:




In [0]:
# Your Code Here#
print(a[np.logical_and(a > 3, a < 11)])

[10]




>(d)  Create an array from the list range(6) and assign it to the variable "b":



In [0]:
# Your Code Here#
b = np.array(range(6))
print(b)

[0 1 2 3 4 5]




>(e)  Use the  *put*  function to replace the first element of "b" with 6:




In [0]:
# Your Code Here#
b.put([0], 6)
print(b)

[6 1 2 3 4 5]




>(f)  Create an array from the list range(5) and assign it to the variable "c":




In [0]:
# Your Code Here#
c = np.array(range(5))
print(c)

[0 1 2 3 4]




>(g)   Use the  *put*  function to replace the first element of "b" with the last element of "c":



In [0]:
# Your Code Here#
b.put([-1], c)
print(b)

[6 1 2 3 4 0]


## Goog Job!!